// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJcIQDkrZAlStNmQO2sZjgPWtAA5OVugk',
    appId: '1:1014051762762:web:b76e0f00dbe44b5a8e2cb3',
    messagingSenderId: '1014051762762',
    projectId: 'flutter-notification-184f0',
    authDomain: 'flutter-notification-184f0.firebaseapp.com',
    storageBucket: 'flutter-notification-184f0.appspot.com',
    measurementId: 'G-H636DE2LCY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaKYCM1Qd_SoYRH57tbmQne7r5z8ojoaI',
    appId: '1:1014051762762:android:1c993470706a81388e2cb3',
    messagingSenderId: '1014051762762',
    projectId: 'flutter-notification-184f0',
    storageBucket: 'flutter-notification-184f0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKQwb4zNSlDtuwqggcPyNtUNkko1Hjslg',
    appId: '1:1014051762762:ios:511e259dc52ef4398e2cb3',
    messagingSenderId: '1014051762762',
    projectId: 'flutter-notification-184f0',
    storageBucket: 'flutter-notification-184f0.appspot.com',
    iosBundleId: 'com.example.flutterProject',
  );
}
